### ISSUE TITLE
Can you write a example of implementation?

### ISSUE THREAD

**Issue by olaferlandsen** [wvezey/feathers-query-filters-aggregate#1]
For example, install and setup:

npm install ... --save

Edit file.... And add ...

**Comment by wvezey** [comment]
Olaf, my apologies for leaving incomplete documentation. I will do this today and close the issue. Thank you for the nudge.

**Comment by wvezey** [comment]
Olaf, the README has been updated. Please let me know if you need anything else.

**Comment by olaferlandsen** [comment]
thanks too much @wvezey, but it only show how to install using npm and whats about setup?
I don't need setup anything? thanks!

**Comment by wvezey** [comment]
Olaf,

Again, I am sorry for the incomplete documentation. I have added the steps
to use in the To Use section of the README file. Please let me know if you
run into any more issues.

Bill

**Comment by olaferlandsen** [comment]
Thanks!
